import type { Player, NewsArticle, StandingEntry, Match, Sponsor } from "@/types";

export const PLAYERS: Player[] = [
  { id: "p1", name: "PATRON", firstName: "Thomas", number: 1, position: "GK", nationality: "FR", stats: { appearances: 22, goals: 0, assists: 1 } },
  { id: "p2", name: "SISSOKO", firstName: "Kévin", number: 5, position: "DEF", nationality: "FR", stats: { appearances: 20, goals: 2, assists: 3 } },
  { id: "p3", name: "BAMBA", firstName: "Youssouf", number: 8, position: "MID", nationality: "CI", stats: { appearances: 24, goals: 5, assists: 7 } },
  { id: "p4", name: "SANTOS", firstName: "Diego", number: 9, position: "ATT", nationality: "BR", stats: { appearances: 23, goals: 14, assists: 4 } },
  { id: "p5", name: "MARTIN", firstName: "Alexis", number: 10, position: "ATT", nationality: "FR", stats: { appearances: 21, goals: 9, assists: 6 } },
  { id: "p6", name: "DIALLO", firstName: "Mamadou", number: 6, position: "DEF", nationality: "SN", stats: { appearances: 22, goals: 1, assists: 2 } },
  { id: "p7", name: "LUCAS", firstName: "Pierre", number: 7, position: "MID", nationality: "FR", stats: { appearances: 20, goals: 4, assists: 8 } },
  { id: "p8", name: "HERNANDEZ", firstName: "Carlos", number: 11, position: "ATT", nationality: "ES", stats: { appearances: 18, goals: 7, assists: 3 } },
];

export const NEWS: NewsArticle[] = [
  {
    id: "n1",
    title: "Victoire éclatante face à Valenciennes : 3-0 !",
    excerpt: "Les Chardons ont dominé de bout en bout cette rencontre cruciale dans la course à la montée. Un collectif souverain.",
    image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&q=80",
    category: "Match",
    publishedAt: "2026-03-01",
    slug: "victoire-valenciennes-3-0",
    isFeatured: true,
  },
  {
    id: "n2",
    title: "Diego Santos prolonge jusqu'en 2028",
    excerpt: "Le meilleur buteur du club a paraphé un nouveau contrat de deux ans. Un signal fort de l'ambition du club.",
    image: "https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=800&q=80",
    category: "Transfert",
    publishedAt: "2026-02-27",
    slug: "santos-prolonge-2028",
    isFeatured: false,
  },
  {
    id: "n3",
    title: "Le derby face à Metz : 5 000 places déjà vendues",
    excerpt: "Le choc de la saison approche à grands pas. Marcel Picot sera une fournaise le 14 mars. Prenez vos places maintenant.",
    image: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&q=80",
    category: "Billetterie",
    publishedAt: "2026-02-25",
    slug: "derby-metz-billets",
    isFeatured: false,
  },
  {
    id: "n4",
    title: "Nouvelle tenue third 2025-2026 dévoilée",
    excerpt: "La troisième tenue, entièrement noire avec des détails dorés, rend hommage à l'histoire centenaire du club.",
    image: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&q=80",
    category: "Club",
    publishedAt: "2026-02-20",
    slug: "tenue-third-2026",
    isFeatured: false,
  },
];

export const STANDINGS: StandingEntry[] = [
  { position: 1,  team: "Angers SCO",          shortName: "ANG", played: 27, won: 17, drawn: 5, lost: 5,  goalsFor: 52, goalsAgainst: 25, goalDiff: 27, points: 56, form: ["W","W","D","W","W"] },
  { position: 2,  team: "Caen",                 shortName: "CAE", played: 27, won: 16, drawn: 4, lost: 7,  goalsFor: 45, goalsAgainst: 28, goalDiff: 17, points: 52, form: ["W","L","W","W","D"] },
  { position: 3,  team: "AS Nancy Lorraine",    shortName: "NAN", played: 27, won: 15, drawn: 6, lost: 6,  goalsFor: 48, goalsAgainst: 30, goalDiff: 18, points: 51, form: ["W","W","W","D","W"], isASNL: true },
  { position: 4,  team: "Guingamp",             shortName: "GUI", played: 27, won: 14, drawn: 6, lost: 7,  goalsFor: 40, goalsAgainst: 27, goalDiff: 13, points: 48, form: ["D","W","W","L","W"] },
  { position: 5,  team: "Rodez AF",             shortName: "ROD", played: 27, won: 13, drawn: 7, lost: 7,  goalsFor: 38, goalsAgainst: 31, goalDiff: 7,  points: 46, form: ["W","D","D","W","L"] },
  { position: 6,  team: "Grenoble",             shortName: "GRE", played: 27, won: 12, drawn: 6, lost: 9,  goalsFor: 36, goalsAgainst: 33, goalDiff: 3,  points: 42, form: ["L","W","D","W","W"] },
  { position: 7,  team: "Bastia",               shortName: "BAS", played: 27, won: 11, drawn: 8, lost: 8,  goalsFor: 34, goalsAgainst: 32, goalDiff: 2,  points: 41, form: ["D","D","W","L","W"] },
  { position: 8,  team: "Paris FC",             shortName: "PFC", played: 27, won: 11, drawn: 6, lost: 10, goalsFor: 33, goalsAgainst: 35, goalDiff: -2, points: 39, form: ["W","L","W","D","L"] },
  { position: 9,  team: "Dunkerque",            shortName: "DKK", played: 27, won: 10, drawn: 8, lost: 9,  goalsFor: 30, goalsAgainst: 34, goalDiff: -4, points: 38, form: ["D","L","W","W","D"] },
  { position: 10, team: "Pau FC",               shortName: "PAU", played: 27, won: 9,  drawn: 7, lost: 11, goalsFor: 28, goalsAgainst: 36, goalDiff: -8, points: 34, form: ["L","D","L","W","D"] },
  { position: 11, team: "Laval",                shortName: "LAV", played: 27, won: 8,  drawn: 9, lost: 10, goalsFor: 27, goalsAgainst: 35, goalDiff: -8, points: 33, form: ["D","W","L","D","L"] },
  { position: 12, team: "Valenciennes",         shortName: "VAL", played: 27, won: 8,  drawn: 6, lost: 13, goalsFor: 25, goalsAgainst: 40, goalDiff:-15, points: 30, form: ["L","L","D","W","L"] },
  { position: 13, team: "SC Bastia",            shortName: "SCB", played: 27, won: 7,  drawn: 7, lost: 13, goalsFor: 24, goalsAgainst: 41, goalDiff:-17, points: 28, form: ["L","L","W","L","D"] },
  { position: 14, team: "Concarneau",           shortName: "CON", played: 27, won: 6,  drawn: 7, lost: 14, goalsFor: 22, goalsAgainst: 44, goalDiff:-22, points: 25, form: ["L","D","L","L","W"] },
  { position: 15, team: "Niort",                shortName: "NIO", played: 27, won: 5,  drawn: 8, lost: 14, goalsFor: 20, goalsAgainst: 46, goalDiff:-26, points: 23, form: ["L","L","D","L","L"] },
];

export const MATCHES: Match[] = [
  {
    id: "m-001",
    homeTeam: "AS Nancy Lorraine",
    awayTeam: "FC Metz",
    date: "2026-03-14",
    time: "20:00",
    competition: "Ligue 2 BKT",
    stadium: "Stade Marcel Picot",
    isHome: true,
    ticketingUrl: "https://billetterie.asnl.fr/prochain-match",
    isHighProfile: true,
    status: "upcoming",
  },
  {
    id: "m-002",
    homeTeam: "Laval",
    awayTeam: "AS Nancy Lorraine",
    date: "2026-03-21",
    time: "15:00",
    competition: "Ligue 2 BKT",
    stadium: "Stade Francis-Le Basser",
    isHome: false,
    status: "upcoming",
  },
  {
    id: "m-003",
    homeTeam: "AS Nancy Lorraine",
    awayTeam: "Gueugnon",
    date: "2026-03-28",
    time: "20:00",
    competition: "Ligue 2 BKT",
    stadium: "Stade Marcel Picot",
    isHome: true,
    ticketingUrl: "https://billetterie.asnl.fr/gueugnon",
    status: "upcoming",
  },
  {
    id: "m-prev1",
    homeTeam: "AS Nancy Lorraine",
    awayTeam: "Valenciennes",
    homeScore: 3,
    awayScore: 0,
    date: "2026-03-01",
    time: "20:00",
    competition: "Ligue 2 BKT",
    stadium: "Stade Marcel Picot",
    isHome: true,
    status: "finished",
  },
  {
    id: "m-prev2",
    homeTeam: "Annecy",
    awayTeam: "AS Nancy Lorraine",
    homeScore: 1,
    awayScore: 1,
    date: "2026-02-22",
    time: "18:00",
    competition: "Ligue 2 BKT",
    stadium: "Stade de Genève",
    isHome: false,
    status: "finished",
  },
];

export const SPONSORS: Sponsor[] = [
  { id: "s1", name: "Crédit Mutuel", logo: "https://via.placeholder.com/160x60/ffffff/C8102E?text=Crédit+Mutuel", url: "#", tier: "platinum" },
  { id: "s2", name: "Grand Est", logo: "https://via.placeholder.com/160x60/ffffff/C8102E?text=Grand+Est", url: "#", tier: "platinum" },
  { id: "s3", name: "Ville de Nancy", logo: "https://via.placeholder.com/160x60/ffffff/C8102E?text=Nancy", url: "#", tier: "gold" },
  { id: "s4", name: "Hummel", logo: "https://via.placeholder.com/120x50/ffffff/C8102E?text=Hummel", url: "#", tier: "gold" },
  { id: "s5", name: "Orange", logo: "https://via.placeholder.com/120x50/ffffff/C8102E?text=Orange", url: "#", tier: "silver" },
  { id: "s6", name: "BNP Paribas", logo: "https://via.placeholder.com/120x50/ffffff/C8102E?text=BNP", url: "#", tier: "silver" },
  { id: "s7", name: "Leroy Merlin", logo: "https://via.placeholder.com/120x50/ffffff/C8102E?text=Leroy+Merlin", url: "#", tier: "official" },
  { id: "s8", name: "Michelin", logo: "https://via.placeholder.com/120x50/ffffff/C8102E?text=Michelin", url: "#", tier: "official" },
];
